### ISSUE TITLE
New 2024.03.4 mac builds are broken

### ISSUE THREAD

**Issue by greglandrum** [conda-forge/rdkit-feedstock#162]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

The SDF parser in the new build (build 1) of the 2024.03.4 release is broken on MacOS (both CPU types).

This came up in an RDKit bug report: https://github.com/rdkit/rdkit/issues/7619

I'm going to try and track down what's going on, but I think we should mark those builds as broken so that people get the build 0 version instead. This would mean no numpy 2.0 support on the Mac, but at at least the SDF parser would work.

### Installed packages

```shell
rdkit 2024.03.4
```

### Environment info

```shell
python 3.12
```

**Comment by greglandrum** [comment]
There's some more info in the comments of https://github.com/rdkit/rdkit/issues/7619, but it looks like this is due to some change between libcxx v18 and v16. It has been fixed on the RDKit master already, so I'm going to move up the 2024.03.5 release in order to get a fix out there.

**Comment by jaimergp** [comment]
Closed by https://github.com/conda-forge/admin-requests/pull/1034
