### ISSUE TITLE
Disable python2 builds for the 2019.03 release cycle

### ISSUE THREAD

**Issue by greglandrum** [conda-forge/rdkit-feedstock#28]
As of the 2019.03 release cycle, the RDKit no longer supports Python 2. We'll keep doing bug fixes with Python 2 builds on the 2018.09 release branch for another year and then turn that off too, so theoretically we could keep doing conda-forge builds against that release branch for a while.

More info about this in the release notes:
https://github.com/rdkit/rdkit/blob/master/ReleaseNotes.md#really-important-announcement

I'm not sure what the best practice is to handle this in conda-forge.

I just did a beta release for 2019.03.1 and hope to do the actual release next Monday or Tuesday.

**Comment by mcs07** [comment]
I believe we can just create a '2018.09' branch in the feedstock, and it will be treated the same as the master branch by all the CI scripts.
