### ISSUE TITLE
Windows builds don't include a bunch of extra libraries

### ISSUE THREAD

**Issue by richardjgowers** [conda-forge/rdkit-feedstock#36]
Mostly related to #15 , the windows builds don't include libraries/headers to link to.  I'm not sure if there's a way to add to this recipe a labelled build which is essentially `rdkit-dev`

**Comment by n-elie** [comment]
Hello,

I am developping a conda package that depends on RDKit and would need the header files to compile on Windows. On Linux and Mac, the headers are present so it's ok. Any idea on how to distribute headers?
