### ISSUE TITLE
Builds on ARM/ppc64le 

### ISSUE THREAD

**Issue by mattwthompson** [conda-forge/rdkit-feedstock#52]
There is some interest in distributing RDKit on other architectures like ARM, ppc64le, and probably others. I believe the infrastructure for supporting them in conda-forge is pretty solid; would there by any expected technical hurdles that make this not worthwhile? If not, I can take a stab at this myself.

Happy to move this over to the main RDKit issue tracker if there are issues outside of packaging that would be roadblockers earlier.

**Comment by jaimergp** [comment]
Let's see what happens!
https://github.com/conda-forge/rdkit-feedstock/pull/54
