### ISSUE TITLE
add support for arm64 on MacOS

### ISSUE THREAD

**Issue by greglandrum** [conda-forge/rdkit-feedstock#63]
I've done local rdkit builds on a Mac with the Apple M1 chip and everything works fine, so I think we can safely make arm64 versions of this recipe available.

From this blog post
https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/
it looks like maybe the only thing we need to do is add the rdkit packages to this list and then the rest will happen automatically?
https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/migrations/osx_arm64.txt

**Comment by greglandrum** [comment]
Thanks @jaimergp . That PR was merged, but no PR has come through here with the suggested changes.
Do you know if there is something else we need to do in order to make that happen?
Or should I just be patient? ;-)

**Comment by jaimergp** [comment]
I am afraid we just need to be patient :)

**Comment by jaimergp** [comment]
The PR is [enqueued](https://conda-forge.org/status/#armosxaddition) (under Awaiting parents). We are waiting on some our dependencies to be available (`pycairo`) first. Their PR is here: https://github.com/conda-forge/pycairo-feedstock/pull/22.

**Comment by l0d0v1c** [comment]
Is it available from conda channel?

**Comment by greglandrum** [comment]
@jaimergp, @mcs07 : I've been thinking about this a bit and have a question/suggestion.

The RDKit doesn't actually *need* pycairo. That dependency is there to support people who are still using the legacy (i.e. non MolDraw2D) drawing code and isn't strictly necessary even for them: if pycairo isn't installed the old drawing code will just fall back to something which produces uglier images.

An RDKit install without pycairo would be 100% functional: it would just produce less attractive renderings when the legacy drawing code is used to produce PNGs. I think that's a reasonable price to pay to allow people who want to use new code on new hardware.

The least "disruptive" suggestion would be to just remove the pycairo depenency on ARM64 Mac builds, but I think it would also be fine to remove it for all Mac builds.

I have not yet done the work to actually deprecate and remove the legacy drawing code, but that's planned for a future release. At this point though, the earliest we could completely remove it is the 2022.03 release.

**Comment by jaimergp** [comment]
Yes, we can skip dependencies conditionally. I'd say we go for the "least disruptive" option now. I don't know if the bot will auto-refresh the dependency graph when that happens, but we can always pin the Conda Forge team if that's not the case.

**Comment by jaimergp** [comment]
Oh, #72 just came in!
