### ISSUE TITLE
Question: most recent compiler versions available in conda-forge

### ISSUE THREAD

**Issue by greglandrum** [conda-forge/rdkit-feedstock#89]
Is there documentation somewhere about which compiler versions are supported when doing conda-forge builds?

I would like to start thinking about a path forward to moving the RDKit to C++20, but definitely don't want to do anything which would cause problems here.

**Comment by mcs07** [comment]
All I know of is https://conda-forge.org/docs/maintainer/infrastructure.html#compilers-and-runtimes and https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/conda_build_config.yaml

**Comment by greglandrum** [comment]
That's already super helpful. At the moment it looks like they have g++-9, clang-11, and MSVC++2017
That wouldn't allow broad use of C++20 features. I'll continue to keep an eye on that though.
