### ISSUE TITLE
Does this work with recent conda versions on the Mac?

### ISSUE THREAD

**Issue by greglandrum** [conda-forge/rdkit-feedstock#9]
I've been struggling with this for quite a while with the standard RDKit conda packages, so I'm wondering if these conda-forge builds work with the most recent versions of conda when run on the Mac.

**Comment by pstjohn** [comment]
I don't think so unfortunately. I can try a more recent version, but I've definitely seen the segfault described in rdkit/rdkit#1617 with a conda-forge built rdkit in the past.

Think its a compiler mismatch? Maybe a feedstock re-render would solve it.

**Comment by pstjohn** [comment]
googling `Fatal Python error: PyThreadState_Get: no current thread` seems to indicate that somewhere a python version is being linked that is not the current version being run. I feel like conda should be able to deal with those linkages, and I'm not sure why it would change between different versions of conda.

I will say that the feedstock is built and tested using conda version 4.3.34. So maybe that's a clue. It doesn't look like we're able to change that at present. (conda-forge/conda-smithy#630)

**Comment by greglandrum** [comment]
hmm, unlucky.
The problems we're having with the recent versions of conda on the Mac have proven to be very difficult to track down and fix; it would have been nice to learn that someone else has already found a solution.

I've got the whole thing reduced down to a small test case and we're going to try and get the attention of someone from anaconda, since it was a change they made that broke things.

**Comment by pstjohn** [comment]
on my end at least rdkit's working on newer mac versions. closing
