### ISSUE TITLE
Latest build boost-cpp=1.74.0 causes "undefined symbol" error when importing rdkit.Chem from Python

### ISSUE THREAD

**Issue by greglandrum** [conda-forge/rdkit-feedstock#93]
There's a problem with the RDKit and the most recent boost-cpp build. With boost-cpp 1.74.0-h359cf19_5 everything is fine, but with boost-cpp=1.74.0=h359cf19_6 I get the following:
```
(rdkit_tmp) glandrum@Badger:~$ python -c 'from rdkit import Chem'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/glandrum/miniconda3/envs/rdkit_tmp/lib/python3.9/site-packages/rdkit/Chem/__init__.py", line 23, in <module>
    from rdkit.Chem.rdmolfiles import *
ImportError: /home/glandrum/miniconda3/envs/rdkit_tmp/lib/python3.9/site-packages/rdkit/Chem/../../../../libRDKitmaeparser.so.1: undefined symbol: _ZN5boost9iostreams4zlib8deflatedE
```
This was originally reported by @guenp in the RDKit repo:
https://github.com/rdkit/rdkit/issues/4987

Is it possible to manually trigger a rebuild of this repo to see if it clears that up?

**Comment by hadim** [comment]
I got the same issue as well. I'll open a PR to trigger a rebuild.

**Comment by hadim** [comment]
@conda-forge/rdkit: should we mark those packages as broken?

**Comment by hadim** [comment]
Pretty sure `boost-cpp=1.74` build 7 (from https://github.com/conda-forge/boost-cpp-feedstock/pull/115) resolves the issue for me so likely for the others too.

Please confirm.

**Comment by greglandrum** [comment]
Yep, that resolves it.
Thanks for noticing @hadim
